### ISSUE TITLE
Allow some way to test nondeterministic error ordering

### ISSUE THREAD

**Issue by CAD97** [dtolnay/trybuild#10]
Certain rustc lints (such as the NLL borrow checker) emit errors in a nondeterministic order.

**Comment by dtolnay** [comment]
Ah, that's too bad. I would accept a PR to consider compile_fail tests passing if they match the expected stderr file modulo ordering of groups of lines that start with `^error\[E[0-9]{4}\]:` up to the next blank line.

**Comment by dtolnay** [comment]
I have not encountered nondeterminism in quite a while.

We can reopen if someone can produce a test case in which rustc (not a proc macro) produces nondeterministically ordered diagnostics.
