### ISSUE TITLE
Check only substring of error message 

### ISSUE THREAD

**Issue by carlomilanesi** [dtolnay/trybuild#103]
To check the whole error message is fragile.
For my need, it is enough to check that the stderr contains the string "`error[E0271]`".
In addition, it would be nice to specify it inline, for example with the following statement:
`t.compile_fail_containing("tests/ui/name*.rs", "error[E0271]");`
An empty error string will mach any error case.

**Comment by dtolnay** [comment]
I would prefer not to build this into this library.
