### ISSUE TITLE
Run passing tests through Miri

### ISSUE THREAD

**Issue by TyPR124** [dtolnay/trybuild#104]
I feel it would be nice to be able to run my passing tests through Miri.

I'm not quite sure how the API should look for that, but I could try to implement something if this seems like a reasonable addition. My first thought is to just have a method like `.miri_pass(path)` that works the same as `.pass(path)`, except using Miri.

Off the top of my head, I can't think of any reason you would want compilation to pass but Miri to fail, so I'm not sure of the need for a failing miri test.

As an extension of this, it would also be nice to be able to run Miri tests for a custom target, mostly as a means to test endian correctness. I'm not sure how trybuild handles custom targets now (if at all) or how realistic this idea is.

Again, if any of this sounds reasonable, I'm willing to work on an implementation.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into trybuild. Passing tests can be run via `cargo miri test` instead, and compile_fail tests don't make sense in miri because they would fail to compile prior to anything miri would do.
