### ISSUE TITLE
Interaction with `-Z instrument-coverage`

### ISSUE THREAD

**Issue by davidhewitt** [dtolnay/trybuild#115]
I'm trying to generate coverage information for PyO3's procedural macros when running under trybuild. (https://github.com/PyO3/pyo3/pull/1577)

I know that trybuild has to do some dancing with directories and environment to work, and I think part of that is interacting negatively with rustc's nightly `-Zinstrument-coverage` switch. I took a quick look into the guts of the trybuild codebase, but I'm not familiar enough with it to have an intuition what might be the cause.

This is what I'm doing with the PyO3 repo (NB if you try to reproduce you'll need to run my branch `compile-errors-on-coverage` from the above PR, as on `main` branch the whole `trybuild` test is currently skipped on nightly to avoid CI churn with diagnostics and differences in `syn` spans):

```bash
CARGO_TERM_VERBOSE=true RUSTFLAGS="-Zinstrument-coverage" LLVM_PROFILE_FILE="$(pwd)/coverage-%p-%m.profraw" cargo +nightly test --test test_compile_error
grcov . --binary-path target/debug/deps/ -s . -t lcov --branch  -o coverage.lcov
genhtml -o ./target/debug/coverage/ --show-details --highlight --ignore-errors source --legend coverage.lcov
```

The output html report in `target/debug/coverage/index.html` shows that no lines on the pyo3 macros crates were hit, which must be incorrect because I can see the trybuild output in the terminal has executed pyo3 code.

Replacing `test_compile_error` in the procedure above with a different test (e.g. `test_pymethods`) yields a correct result where the macros do indeed show coverage information.

My guess is that `trybuild` having a separate `--target` directory is likely to be the root cause, but some quick experimentation with this myself (e.g. pointing the `grcov` invocation to the different directory) hasn't yielded any results.

Thanks in advance for any help with this.

**Comment by jhpratt** [comment]
I'd very much like to see this fixed. While compiletest works (including for LLVM coverage), it is too difficult to even link to the crate being tested. I managed to get it to work on my machine, but it failed in CI on another OS. Upon switching to trybuild, LLVM coverage is nonexistent. Additionally, I can't _just_ test the error message, but rather must have a full UI test. As UI tests don't have stable format, there's no "correct" way to both test this on stable and have it work with `-Zinstrument-coverage`, which requires nightly.

**Comment by davidhewitt** [comment]
> As UI tests don't have stable format, there's no "correct" way to both test this on stable and have it work with -Zinstrument-coverage, which requires nightly.

My vision in PyO3 was to run the UI tests as regression tests on stable, and separately use them for coverage on nightly. On the nightly run I would ignore any failing UI tests; I'd still get the desired coverage information even if the compiler output changed.

**Comment by jhpratt** [comment]
That was my plan as well. The issue regarding `-Zinstrument-coverage` still exists regardless, though. It's more an observation that compiletest has some functionality that trybuild doesn't, but it's not a huge deal.

**Comment by jhpratt** [comment]
@dtolnay Anything I can do to help here? This is the only reason I haven't switched from compiletest-rs to trybuild, and there are notable issues with the former in my experience.

**Comment by dtolnay** [comment]
I would be prepared to review a completed PR that fixes this without breaking existing use cases, but I definitely don't plan to look into this myself.

**Comment by jhpratt** [comment]
Okay. I'll probably look into this at some point myself in that case.
