### ISSUE TITLE
1.0.47 seems to have regressed #85

### ISSUE THREAD

**Issue by ahl** [dtolnay/trybuild#136]
I tested all releases from 1.0.46 through 1.0.50 and 1.0.46 was the last release that elided line numbers for `$WORKSPACE` files. I see that this seems to be functionality `trybuild` seeks to preserve: https://github.com/dtolnay/trybuild/pull/110#discussion_r567139988

An example of the output can be found here:
https://github.com/oxidecomputer/dropshot/pull/140/files

I'm not sure if or how one might add testing for this in the `trybuild` repo, but I'd be happy to submit a PR if pointed in the right direction.

Thank you @dtolnay as always for your work!

**Comment by dtolnay** [comment]
Good call. Recent nightly rustc has started getting more willing to paste trait impls and function signatures from other crates into diagnostic output (including after `-->` surprisingly, not just after `:::` &mdash; see https://github.com/dtolnay/trybuild/pull/128#issue-1019587949), which means we've had to try to get more discerning about what paths come from inside the same crate vs from other crates. In the case of `$WORKSPACE/dropshot/src/api_description.rs` vs `src/api_description.rs` it's now noticing that as coming from inside the same crate whose test suite is being run, and not hiding line numbers, which is consistent with the comment you linked.

I agree this isn't correct behavior; we want to be able to move code in `api_description.rs` up or down without touching the ui test.

I think it's probably time to renege on this comment from #85:

> I am not a fan of \[indiscriminately concealing all line numbers\] since I find it breaks the immersion and makes it harder for a human reader to visually perceive the file as a user-facing compiler diagnostic that's worth critically evaluating and improving, as opposed to a test.

and just hide all line numbers everywhere, or hide all except the one top-level file the ui test was invoked on.

**Comment by ahl** [comment]
With the release of Rust 1.56 this has become more acute for us. Would you accept a PR for this? Happy to do it, and any guidance would be welcome. Thanks.
