### ISSUE TITLE
Some changes made trybuild stop substituting $DIR

### ISSUE THREAD

**Issue by Ploppz** [dtolnay/trybuild#140]
I was working on the `diesel` crate.
The compile fail tests reported a lot of stderr diffs.
While many of the differences make sense, a lot of those diffs are like:
```
531c531
<    --> $DIR/selectable.rs:195:52
---
>    --> tests/fail/selectable.rs:195:52
```
My changes are in this commit https://github.com/Ploppz/diesel/commit/4854d0410d102fc75e3da7b8b2391d5c720a034f
To reproduce, `cd diesel_compile_tests; cargo test`. Maybe you will have to start postgres database like this https://github.com/diesel-rs/diesel/blob/master/CONTRIBUTING.md#setting-up-diesel-locally

**Comment by dtolnay** [comment]
I think this is behaving correctly &mdash; the diesel_compile_tests pass on my machine on the current master branch of diesel. The normalizations that trybuild applies are always changing to smooth over differences in rustc's diagnostic output across rustc versions, and in general we do normalization in a way that makes an old captured \*.stderr file succeed if it matches the normalization logic of any previous trybuild release. When the error messages change independently of a rustc change though, like in your diesel code change, you regenerate the affected \*.stderr files and typically you'd want that to run the most recent normalization logic.

**Comment by Ploppz** [comment]
Sorry, I don't quite understand why it stopped substituting `tests/fail` for `$DIR`, could you elaborate?

**Comment by dtolnay** [comment]
> So basically you are saying that `TRYBUILD=overwrite` updates all stderr files to the new output

> their changes may result in updates to completely unrelated test cases

I am not saying that. It updates affected tests only i.e. ones that fail. I believe this all already works the way that you are requesting.

**Comment by weiznich** [comment]
:+1: That's correct. I've rechecked that with @Ploppz and there are other changes as well (which I was not aware of before). So sorry for the confusion, you are right, that's the correct behaviour :+1:
