### ISSUE TITLE
$DIR and $WORKSPACE removed in output, causing CI failure

### ISSUE THREAD

**Issue by AzureMarker** [dtolnay/trybuild#141]
Due to #132 the output format changed but the version was kept at 1.0.x, causing many trybuild tests to fail when upgraded to the latest version. Since libraries don't normally check in `Cargo.lock`, this caused my UI tests to fail in CI. This isn't a big deal, but it's unexpected and seems to be unintended based on the comment I reference below.

This is related to #140, though different because the only change in the output is the switch from `$DIR` to relative path.

According to this comment, it sounds like trybuild should not raise a mismatch in this case:
> The normalizations that trybuild applies are always changing to smooth over differences in rustc's diagnostic output across rustc versions, and in general we do normalization in a way that makes an old captured *.stderr file succeed if it matches the normalization logic of any previous trybuild release.

https://github.com/dtolnay/trybuild/issues/140#issuecomment-959611298

Link to CI where the mismatch occurs:
https://app.circleci.com/pipelines/github/AzureMarker/shaku/8/workflows/0db93ae3-9ee0-4b77-ac18-94008f9aa5b3/jobs/17

**Comment by dtolnay** [comment]
It's expected that the test outputs occasionally change. This is the nature of ui tests. We make some effort to prevent things changing spuriously, but as long as the rate of change from trybuild normalization logic is small relative to the rate of change from diagnostics changes upstream in rustc, this doesn't seem like an issue.

**Comment by AzureMarker** [comment]
I took another look at the test outputs that changed, and they all included `$WORKSPACE`. The tests that only included `$DIR` did not change. So there was some effort made to avoid changing the output, but `$WORKSPACE` was missed.
