### ISSUE TITLE
Have a way to show all acceptable variations

### ISSUE THREAD

**Issue by mhammond** [dtolnay/trybuild#142]
Thank you for this tool ❤️ We are using it in https://github.com/mozilla/uniffi-rs/, and something that's probably unique to that tool is that we are testing the output in *generated* rust code - and it's generated under the crate's `./target` directory.

Long story short, when we needed to update the .stderr file, using `TRYBUILD=overwrite` shows that one of the lines changed from

> --> $DIR/counter.uniffi.rs:160:13
to
> --> $WORKSPACE/target/debug/build/uniffi_uitests-6472345683e61af2/out/counter.uniffi.rs

Which clearly isn't going to work in practice - and I could not hand-edit it into anything acceptable. After arranging to run trybuild from a source checkout and instrumenting it to show all acceptable variations, I chose one using $DIR and life was good.

It would be ideal if there was some way to show the variations that work even if it's not the preferred. My first thought was to allow, say, `TRYBUILD=diagnose`, which would just print all variations, and while that's not a perfect fit, particularly in the case when stderr doesn't exist, it might be close enough.

I'm happy to put a PR up for this, but thought I'd open this issue to get feedback on the preferred approach or to see if I'm missing something obvious.

Edit: I should have noted that the `6472345683e61af2` in the output is a hash generated by that tool and will change in various cases.

**Comment by dtolnay** [comment]
Old variations are only supposed to be used by old preexisting stderr files.

I put up #143 to normalize the out dir path to `$OUT_DIR[uniffi_uitests]/counter.uniffi.rs` so that it's agnostic to the hash and build profile.

**Comment by mhammond** [comment]
That works perfectly, thank you.
