### ISSUE TITLE
`compile_fail` compilation failing to fail

### ISSUE THREAD

**Issue by U007D** [dtolnay/trybuild#148]
Let me start by thanking you @dtolnay for your tireless efforts and contributions to the Rust community!

I am working on an experimental ranged types crate with typestatey/compile-time checks.  One of those checks is an [invariant which ensures the `END` bound is not less than the `START` bound](https://github.com/U007D/trybuild_test/blob/main/src/range.rs).

I created a `trybuild` test and was surprised when `compile_fail` reported a test failure because the [test code](https://github.com/U007D/trybuild_test/blob/main/tests/trybuild/range_test.rs) actually compiles successfully, when it shouldn't.

I tried extracting the [same code as a unit test](https://github.com/U007D/trybuild_test/blob/main/src/range/unit_tests/range_test.rs), [as an integration test](https://github.com/U007D/trybuild_test/blob/main/tests/integration_tests.rs) and [as a standalone package](https://github.com/U007D/trybuild_test/tree/main/tests/standalone/range_test).  In each of these cases, the test code failed to compile, which is what I was expecting.

I am at a loss to explain why the compilation succeeds under `trybuild`, so I am working though debugging `trybuild` to see what might be wrong.  So far, I have determined that `trybuild` is invoking the test with `"<path to cargo>/cargo" "--offline" "build" "--target" "x86_64-apple-darwin" "--bin" "trybuild-tests" "--no-default-features" "--features" ""` which all *seems* fine.  Issuing this command line manually fails to find `trybuild-tests`, so I am working on getting `trybuild` to leave behind the compilation project so that I can examine it, but have not yet succeeded.

I thought that in parallel, I would post a [minimal compiling reproducible example](https://github.com/U007D/trybuild_test) of the issue and the three tests to highlight the inconsistency and provide context in case there was something simple I am missing and someone with more experience with `trybuild` could point out what I am missing.

Thanks in advance!
U007D

**Comment by dtolnay** [comment]
I think this is behaving correctly. If you run `cargo check --test integration_tests`, the same code also compiles there.

**Comment by U007D** [comment]
Interesting.  `cargo check --test integration_tests` does indeed pass, but `cargo build --test integration_tests` fails (as does `cargo test`/`cargo test --test integration_tests`).

Perhaps `trybuild` is emitting a `cargo check` for my test after all?  According to `run.rs` it appears `trybuild` will use `cargo check` if `project.has_pass` is false, which appears to be the case if I am expecting a compilation failure.

Is there some way to force a `cargo build` from `trybuild`?

**Comment by U007D** [comment]
```bash
[I] sergibli@HephaestusMobi ~/D/b/trybuild_test (main) [101]> cargo check --test integration_tests
    Checking trybuild_test v0.1.0 (/Users/sergibli/Development/bg/trybuild_test)
warning: unused variable: `result`
  --> tests/integration_tests.rs:14:9
   |
14 |     let result = Range::<START, END>;    // Invalid `Range`
   |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_result`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `trybuild_test` (test "integration_tests") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.67s
[I] sergibli@HephaestusMobi ~/D/b/trybuild_test (main)> cargo build --test integration_tests
   Compiling trybuild_test v0.1.0 (/Users/sergibli/Development/bg/trybuild_test)
warning: unused variable: `result`
  --> tests/integration_tests.rs:14:9
   |
14 |     let result = Range::<START, END>;    // Invalid `Range`
   |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_result`
   |
   = note: `#[warn(unused_variables)]` on by default

error[E0080]: evaluation of `trybuild_test::Range::<100_i32, 1_i32>::INVARIANT` failed
 --> /Users/sergibli/Development/bg/trybuild_test/src/range.rs:8:27
  |
8 |     const INVARIANT: () = assert!(START <= END);
  |                           ^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: START <= END', /Users/sergibli/Development/bg/trybuild_test/src/range.rs:8:27
  |
  = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

note: the above error was encountered while instantiating `fn <trybuild_test::Range<100_i32, 1_i32> as std::ops::Drop>::drop`
   --> /Users/sergibli/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:188:1
    |
188 | pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
warning: `trybuild_test` (test "integration_tests") generated 1 warning
error: could not compile `trybuild_test` due to previous error; 1 warning emitted
[I] sergibli@HephaestusMobi ~/D/b/trybuild_test (main) [101]> cargo test --test integration_tests
   Compiling trybuild_test v0.1.0 (/Users/sergibli/Development/bg/trybuild_test)
warning: unused variable: `result`
  --> tests/integration_tests.rs:14:9
   |
14 |     let result = Range::<START, END>;    // Invalid `Range`
   |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_result`
   |
   = note: `#[warn(unused_variables)]` on by default

error[E0080]: evaluation of `trybuild_test::Range::<100_i32, 1_i32>::INVARIANT` failed
 --> /Users/sergibli/Development/bg/trybuild_test/src/range.rs:8:27
  |
8 |     const INVARIANT: () = assert!(START <= END);
  |                           ^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: START <= END', /Users/sergibli/Development/bg/trybuild_test/src/range.rs:8:27
  |
  = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

note: the above error was encountered while instantiating `fn <trybuild_test::Range<100_i32, 1_i32> as std::ops::Drop>::drop`
   --> /Users/sergibli/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:188:1
    |
188 | pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
warning: `trybuild_test` (test "integration_tests") generated 1 warning
error: could not compile `trybuild_test` due to previous error; 1 warning emitted
```
