### ISSUE TITLE
Different output for different compiler versions

### ISSUE THREAD

**Issue by bkchr** [dtolnay/trybuild#15]
Hey,
I'm mostly developing with nightly on my local machine, but CI is using stable. Now, nightly introduced some new output and the tests are failing locally. Is there build in feature so support different outputs per compiler version?

**Comment by dtolnay** [comment]
You could use [select-rustc](https://github.com/dtolnay/select-rustc) to run a different set of ui test files on different compiler versions.

In my crates I tend to run ui tests only on nightly because keeping and checking the historical formatting of the errors is not useful.

```rust
#[rustc::nightly]
#[test]
fn ...
```

**Comment by bkchr** [comment]
Ty :)
