### ISSUE TITLE
How to print something out to stdout continuously after test cases are passed?

### ISSUE THREAD

**Issue by hyunsooda** [dtolnay/trybuild#154]
Hi all,

Once a test case was passed, print something to `stdout` is not shown. It seems intended behavior, but I have no idea how it could be off. Anyone who resolved it? Thank you.

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community.
