### ISSUE TITLE
That `.stderr` files are missing results merely in a warning allows forgetting to check them in

### ISSUE THREAD

**Issue by Samyak2** [dtolnay/trybuild#169]
Thank you for the crate! We're using it in [michie](https://github.com/mobusoperandi/michie).

We ended up merging a PR that adds a new `compile_fail` test and omits the corresponding `.stderr` file. Perhaps missing `.stderr` files could fail the test instead of warn? That should prevent such an error.

@mightyiam

**Comment by mightyiam** [comment]
Thank you, @dtolnay !
