### ISSUE TITLE
Provide mechanism to disable test execution

### ISSUE THREAD

**Issue by davidbarsky** [dtolnay/trybuild#19]
Hi! I'm using Trybuild to test some procedural macros in the [AWS Lambda Runtime for Rust](https://github.com/awslabs/aws-lambda-rust-runtime/pull/111), and I'm really liking it!

 I do have a question, though: there any way to disable [TestCases::pass](https://github.com/dtolnay/trybuild/blob/b4f0b4e02ae90ace151c9147c0ae9fc39503a044/src/lib.rs#L256) from _running_ the code under test/providing a mechanism to _only_ check for compiler errors? 

At runtime, the macro I'm testing with Trybuild makes several assumptions about its environment that include a running server + several environment variables. This results in tests failing with a server connection error, rather than passing due to correct usage of the macro. More concretely, it'd be really handy for my use case if [`run_test`](https://github.com/dtolnay/trybuild/blob/b4f0b4e02ae90ace151c9147c0ae9fc39503a044/src/cargo.rs#L64) would pass `check` rather than `run` to Cargo.

Thanks again for this crate! It's _really_ nice to use, and the test reports are beautifully rendered.

**Comment by dtolnay** [comment]
Could you move the main function out of the root module and provide an empty main instead? If not, I think you may be able to bypass main as the entry point by adding:

```rust
#![feature(start)]

#[start]
fn start(_argc: isize, _argv: *const *const u8) -> isize {
    0
}
```

**Comment by davidbarsky** [comment]
> Could you move the main function out of the root module and provide an empty main instead?

Not really; the procedural macro I'm testing (`#[lambda]`) is intended to be invoked in normal usage as:

```rust
#![feature(async_await)]

use lambda::{lambda, Error};

#[lambda]
#[runtime::main]
async fn main(s: String) -> Result<String, Error> {
    Ok(s)
}
```

> If not, I think you may be able to bypass main as the entry point by adding: [code redacted]

Thanks! That did the trick with:

```rust
#![feature(async_await, start)]

use lambda::{lambda, Error};

#[lambda]
#[runtime::main]
async fn main(s: String) -> Result<String, Error> {
    Ok(s)
}

#[start]
fn start(_argc: isize, _argv: *const *const u8) -> isize {
    0
}
```

Bit curious—why does Trybuild execute the procedural macro instead of only building?

**Comment by slinkydeveloper** [comment]
I had the same problem, fixed adding start method.
