### ISSUE TITLE
Unable to use trybuild with macros that read files

### ISSUE THREAD

**Issue by msrd0** [dtolnay/trybuild#202]
First of all, thanks for this amazing tool!

I'm trying to test a macro which reads files from the source directory of the crate. It reads the `CARGO_MANIFEST_DIR` environment variable (please let me know if there's a better way to do this) and resolves files relative to that directory. Unfortunately, with trybuild it points to `$DIR/target/tests/<crate-name>`, which doesn't contain the files I need.

Is it possible to have `CARGO_MANIFEST_DIR` point to the manifest that defines the test, or to the directory where the test file is located in?

**Comment by dtolnay** [comment]
You should use:

```rust
std::env::set_var(
    "CARGO_MANIFEST_DIR_OVERRIDE",
    std::env::var_os("CARGO_MANIFEST_DIR").unwrap(),
);
```

at the top of your #\[test\] that runs trybuild and then this in the macro:

```rust
let cargo_manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR_OVERRIDE")
    .or(std::env::var_os("CARGO_MANIFEST_DIR"))
    .unwrap();
```

**Comment by msrd0** [comment]
This works, thanks. Just one problem that I noticed: My macro outputs "Help: Searching in directory $CARGO_MANIFEST_DIR" when the file it was looking for doesn't exist, which by its nature, will not always be the same path. However, trybuild for some reason doesn't replace that directory with `$DIR` but leaves the path untouched. Previously, it would output `$DIR/target/tests/<crate-name>` so maybe there's a problem where `$DIR` isn't used when there's no additional path segments behind it?

**Comment by dtolnay** [comment]
Filed separately as #204.
