### ISSUE TITLE
Edition and MSRV with trybuild

### ISSUE THREAD

**Issue by TedDriggs** [dtolnay/trybuild#203]
[`derive_builder`](https://github.com/colin-kiegel/rust-derive-builder) uses trybuild and has started getting CI failures on its MSRV of 1.40 because `once_cell` is using the 2021 edition. Happily, we're only using `trybuild` with 1.59, so I think this problem goes away if I can find a way to avoid 1.40 ever encountering the `trybuild` dependency.

Unfortunately, rust-lang/cargo#1596 doesn't seem to have any movement, so I'm a bit stumped on how to proceed.

My first thought was to move these tests to their own crate, but I don't know if there's a good way to conditionally include a crate in a workspace so I'm not sure if that actually changes anything for me.

**Comment by dtolnay** [comment]
https://github.com/rust-lang/cargo/issues/1596#issuecomment-962730780 describes an idiom for optional dev-dependencies.

**Comment by TedDriggs** [comment]
Can that be used to target a particular rust version?

**Comment by dtolnay** [comment]
Yes if your CI only enables `cfg(skip_ui_tests)` on particular rust versions.
