### ISSUE TITLE
How to test compile-time panics?

### ISSUE THREAD

**Issue by QuarticCat** [dtolnay/trybuild#205]
```rust
struct Foo;

impl Foo {
    const _CHECK: () = assert!(1 > 2);
}

fn main() {
    let _ = Foo::_CHECK;
}
```

This code will panic at compile-time but `trybuild` tells me that `Expected test case to fail to compile, but it succeeded.`

**Comment by QuarticCat** [comment]
However, this test works as expected. Weird.

```rust
const _: () = assert!(1 > 2);

fn main() {}
```

**Comment by dtolnay** [comment]
I think this is behaving correctly. What you've written is not a reliable way to elicit a compile time panic because a const is not necessarily evaluated at compile time, as long as it type-checks.

**Comment by QuarticCat** [comment]
Is there any reliable way to do static asserts? Especially the asserts contain some generic parameters?
