### ISSUE TITLE
how to specify that tests should be run with particular cfg directives?

### ISSUE THREAD

**Issue by sam0x17** [dtolnay/trybuild#206]
I have a piece of code that was previously asserted to be a "pass" example i.e.:
```rust
let t = trybuild::TestCases::new();
t.pass("tests/pallet_ui/pass/*.rs");
```

Now I have one example where one of the macros being tested is set up to throw a compiler error if it is not compiled in test mode. The problem is I can't seem to find any way to tell trybuild to set the `test` directive on a particular example. How can I do this? I'm hoping for something like this:

```rust
let mut t = trybuild::TestCases::new();
t.pass("tests/pallet_ui/pass/*.rs");
t.set_cfg("test");
t.pass("tests/pallet_ui/pass_test_mode/*.rs");
```

Is there an existing way to do this? I can't find anything in the docs but I imagine it's something people frequently need

**Comment by dtolnay** [comment]
I would prefer not to support this in this crate, but it would be reasonable for someone else to maintain a more fully featured fork that serves this situation.

**Comment by sam0x17** [comment]
googlers: the workaround is this:
```rust
std::env::set_var("RUSTFLAGS", "--cfg test");
```
