### ISSUE TITLE
Some environment-dependent paths are included in `.stderr` output

### ISSUE THREAD

**Issue by joshlf** [dtolnay/trybuild#207]
[This build failure](https://github.com/google/zerocopy/actions/runs/3448300170/jobs/5755202337) is caused by the fact that the source code for a dependent crate (`zerocopy`) lives at a different location during testing compared to the one it lived at when the `.stderr` file was initially generated. The diff between the output (in the `GOT` file) and the expected output (in the `WANT` file) is:

```text
$ diff GOT WANT
58c58
<    --> /home/runner/work/zerocopy/zerocopy/src/lib.rs:433:29
---
>    --> /usr/local/google/home/joshlf/workspace/zerocopy/src/lib.rs:433:29
143d142
< 
```

It would be great if there were some way for trybuild to be agnostic to these sorts of environment details.

**Comment by dtolnay** [comment]
This is specific to path dependencies across workspace boundaries, and I am not interested in changing the behavior to accommodate them.
