### ISSUE TITLE
Document usage with multiple toolchains

### ISSUE THREAD

**Issue by 71** [dtolnay/trybuild#211]
I use GitHub actions to test a crate with both its MSRV and the latest nightly. Many internal details change with the nightly API, so I want to test the crate both at its MSRV and at its nightly version. Using any version of Rust should lead to similar error messages, but there are often subtle changes between Rust versions that make them different.

I'd like to use `trybuild` for both MSRV and nightly tests, but since the same `.stderr` files are shared, that doesn't seem possible. #76 would help, but will not be implemented. Is there any other recommended way of dealing with this issue? For now, I simply disable the `trybuild` test in nightly builds, but this is a little worrying.

**Comment by dtolnay** [comment]
In my crates I prefer to run ui tests against nightly only.
