### ISSUE TITLE
Trybuild fails to use `[patch]` from a `$WORKSPACE/.cargo/config.toml`

### ISSUE THREAD

**Issue by kurtbuilds** [dtolnay/trybuild#221]
I have a project (https://github.com/kurtbuilds/oasgen is where I experienced this) with a top level workspace, call that `$WORKSPACE`, and have trybuild tests in `$WORKSPACE/oasgen`. I was doing development on a local dependency of `oasgen` (the package), so I had a `[patch.crates-io]` line in a `$WORKSPACE/.cargo/config.toml` file (not in `$WORKSPACE/oasgen/.cargo/config.toml` - if that file exists, the compiler complains about non-workspace patch settings.) 

When running trybuild tests, I got this confusing behavior where:

1: The initial compiler pass runs correctly. In my situation, I was added a new method to an object defined in the dependency. If I named the method incorrectly in the test, the compiler would suggest the right name, so the compiler obviously picked up the `[patch.crates-io]` line.

2. However, the `trybuild` compiler pass would then fail, with a method not found error.

This caused the rather unfortunate situation where, the compiler would suggest the correct name for the method call, I'd fix the call, and then it'd fail to find the method name I just corrected it to!

I assume the issue exists for other `.cargo/config.toml` positions: https://doc.rust-lang.org/cargo/reference/config.html .

**Comment by dtolnay** [comment]
I was not able to reproduce this. Since trybuild writes the generated Cargo.toml for the test files into somewhere in $WORKSPACE/target, and since Cargo looks in all parent directories for .cargo and merges them together, all the patches from $WORKSPACE/.cargo/config.toml do apply. You will need provide a git commit and a command that someone can just check out and run to reproduce the issue.

**Comment by kurtbuilds** [comment]
I think what happened here is I was running tests on the "master" crate in the workspace, and it depended on the patched version. However, the master crate depended on another crate in the workspace, and that crate itself depended on an old version of the same package. Since it was an old version, it wasn't picking up the feature. However, since the more recent version was used by the "master" crate - the patch wasn't causing the compiler error message about "unused patch lines".

Thank you for looking at it. I'll close this.
