### ISSUE TITLE
Support passing environment into a test

### ISSUE THREAD

**Issue by kurtbuilds** [dtolnay/trybuild#222]
I'm using trybuild to test [`ormlite`](https://github.com/kurtbuilds/ormlite). It uses environment variables to tell it where to detect ORM models (mostly, to understand ORM joins).

This dependence on environment variables, which come from the test runner's process, causes state that requires me to pass `--test-threads=1` when I'm running the tests.

However, if TestCases has functionality to set the environment of their child process, it would eliminate this state dependence and allow me to remove `--test-threads=1`.

LMK if you're open to this feature, and I'd be happy to submit a PR.

**Comment by dtolnay** [comment]
I would prefer not to support this in this library, but it would be reasonable for someone else to maintain a more fully featured fork that serves this situation.
