### ISSUE TITLE
Support filtering the tests that are run (dynamically)

### ISSUE THREAD

**Issue by sunjay** [dtolnay/trybuild#23]
Thanks for the great crate! I'm using this to test a custom derive macro and really enjoying it. :)

It would be very useful if it were possible to filter the tests that run. I'm looking for similar functionality to `cargo test -- foo`. I would be totally fine with this being done through an environment variable similar to how `TRYBUILD=overwrite` is an environment variable.

This is really great when you have lots of tests and want to hone in on a single test or just a few tests that you're fixing all at once. My current workaround is to just comment out my `t.compile_fail("tests/ui/*.rs");` line and replace it with just the tests I want to run. It would be really nice to be able to do this without modifying the source and recompiling.

**Comment by DevinR528** [comment]
I agree this would be nice. I'm pretty sure this would only be possible through an environment variable. If @dtolnay  agrees I can attempt it by filtering the Vec<Test> after expand_globs?

**Comment by dtolnay** [comment]
I would accept a PR for this. I would lean toward using a command line arg instead of env var, like maybe `cargo test -- compile_tests trybuild=tuple_structs.rs`.

**Comment by dtolnay** [comment]
Implemented in 1.0.11.

```
$ cargo test -- compile_tests trybuild=tuple_structs.rs
```

The first argument after "--" must be the trybuild test name i.e. the name of the function that has the #\[test\] attribute and calls trybuild. That's to get Cargo to run the test at all. The next argument starting with "trybuild=" provides a filename filter. Only test cases whose filename contains the filter string will be run.
