### ISSUE TITLE
Different results on mac vs linux

### ISSUE THREAD

**Issue by mirosval** [dtolnay/trybuild#232]
Basically it looks like I get 3 lines more context on mac than I get on Linux. I get the same difference using Docker and on CI, the extra lines look like this:
```
   |
   |     pub fn push(&mut self, value: T) {
   |            ^^^^
```

Is this expected, or is there anything I can do about it? I've already given up on trying to make this work across different toolchains, as the errors are always changing, but at least stable should work, right?

The whole project is here: https://github.com/mirosval/valibuk
An example failing build: https://github.com/mirosval/valibuk/actions/runs/4671776919/jobs/8273173856
Here's the change that fixed the failure: https://github.com/mirosval/valibuk/commit/24bde61a4e0e0ba89282157c51b5c474ed23cc68#diff-8589ce9fe6c5cc6505e9bd68ed277e6fd2e598146ff76f7aef28471484fe651dL24-L26

**Comment by dtolnay** [comment]
Most likely you have different rustup components installed on the different platforms in your CI. Check whether `rustup component add rust-src --toolchain ${{matrix.toolchain}}`  or `rustup component remove rust-src --toolchain ${{matrix.toolchain}}` synchronizes them.
