### ISSUE TITLE
Testing with clippy?

### ISSUE THREAD

**Issue by peter-kehl** [dtolnay/trybuild#235]
Not a mainstream use case: To test that some code fails `cargo clippy`. (OK to restrict/specialize for Github Actions, and locally on Linux/Mac OS.) Any feasible way, please?

(The actual use case: Internal tests of a crate generating attribute macros that inject `#[allow(clippy::xyz...)]`.)

Based on https://github.com/dtolnay/trybuild/issues/13 I assume we can't use clippy driver, since `trybuild` invokes `cargo` instead of `rustc`. Or, could this somehow replace `cargo ...` with `cargo clippy`?

Any ready-to-use alternatives? (I understand I don't want `compiletest` - thx for explaining in #13). 

If no, could having a simple bash script invoke `cargo clippy` and compare the exit value be the simplest way? (I could narrow down/specialize the "test" crates to have 1 clippy lint checked per crate, so "failed/not failed" would be enough information and I could ignore any output. Or could that be fragile?)

Or, how about `CARGO_HOME` and/or `RUSTC_WRAPPER` or any other tricks, please?

**Comment by dtolnay** [comment]
`RUSTC_WORKSPACE_WRAPPER=clippy-driver cargo test` should be sufficient to make the UI tests get built by clippy. Or `std::env::set_var("RUSTC_WORKSPACE_WRAPPER", "clippy-driver");` in the test function that calls trybuild.

You would also need to put `#![deny(clippy::all)]` (or more specific attribute) into each UI test if you want to compare clippy output against a stderr file.
