### ISSUE TITLE
Allow to specify a custom suffix on `TestCases`

### ISSUE THREAD

**Issue by ModProg** [dtolnay/trybuild#245]
I like to test my error messages on both stable and nightly, especially because spans are currently less capable on stable, and I want to try to produce the most useful error messages with both compilers (e.g., I'd use joined spans on nightly, and two separate error messages on stable).

I propose an ability to set a custom suffix/some other ability to mark files on the `TestCases` struct, i.e.:

```rs
let t = TestCases::new().with_custom_suffix("nightly");
t.compile_fail("tests/ui/*.rs"); // results in some other output path, e.g. `*.nightly.stderr` or just `*.nightly`
```

This would also address #84, #71.

**Comment by ModProg** [comment]
I'd be willing to write a PR for this, If you'd consider supporting something like this.

**Comment by dtolnay** [comment]
I would prefer not to support this in this crate. You could look for a more fully featured fork, or add code in the test to rename the right set of files to .stderr before calling into trybuild.
