### ISSUE TITLE
Support `-Zui-testing`

### ISSUE THREAD

**Issue by madsmtm** [dtolnay/trybuild#248]
When running with `RUSTFLAGS="-Zui-testing"` `rustc` replaces line numbers in the side by "LL".

Perhaps `trybuild` could support this? Either by adopting the same format as `-Zui-testing`, or by supporting stripping the "LL" characters as well? (I think it's just an addition to https://github.com/dtolnay/trybuild/blob/aa98d35bbca8670d74f598a08c4c12177e6bb56e/src/normalize.rs#L420)

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate. But it would be reasonable for someone else to maintain a more fully featured ui testing library that could handle this.
