### ISSUE TITLE
Print diff along with expected/actual output

### ISSUE THREAD

**Issue by CreepySkeleton** [dtolnay/trybuild#25]
Sometimes it's really hard to see what's different between expected/actual output. I propose (opt-in?) to print one more message - diff.

**Comment by dtolnay** [comment]
Thanks, I would accept a PR to print a diff if the number of lines changed is 10% or less of the minimum of the total lines before and total lines after.

**Comment by CreepySkeleton** [comment]
@dtolnay Could you please assign me to this? Just so it displays in my dashboard. I'll get to it *sometime* this week.
