### ISSUE TITLE
Select a different target than host

### ISSUE THREAD

**Issue by romancardenas** [dtolnay/trybuild#256]
Hi! I wonder if there is a way to use this crate but building over a different target than the host system (e.g., `riscv32imac-unknown-none-elf`). This would be specially useful for the Rust Embedded community.

Thanks in advance!

**Comment by dtolnay** [comment]
This is not supported by this library, but it would be reasonable for someone else to maintain a more fully featured ui testing library that could handle this.

**Comment by taiki-e** [comment]
This could probably be done without changes to trybuild by setting the `CARGO_BUILD_TARGET` environment variable before calling `TestCases::{pass,compile_fail}`.

**Comment by romancardenas** [comment]
Thanks! I'll try this and integrate it with GitHub CI. Hopefully it does the trick
