### ISSUE TITLE
Normalize `CARGO_PKG_VERSION`

### ISSUE THREAD

**Issue by davidhewitt** [dtolnay/trybuild#279]
In PyO3 we've started adding error messages which look like the following, printing links to versioned documentation:

```
error: #[pyclass] cannot have lifetime parameters. For an explanation, see https://pyo3.rs/v0.22.1/class.html#no-lifetime-parameters
 --> tests/ui/reject_generics.rs:9:27
  |
9 | struct ClassWithLifetimes<'a> {
  |                           ^^
```

The downside of doing this is that the UI test needs updating every time we cut a release.

Would you be open to a PR which adds a normalization to replace the current version with `$VERSION`?

e.g. to make the link `https://pyo3.rs/v$VERSION/class.html#no-lifetime-parameters`

----

If you don't think this normalization is suitable for general use in `trybuild`, is there a possible alternative to allow custom normalisations to be defined in my test suite?

**Comment by dtolnay** [comment]
I think I would prefer not to build anything for this into this crate.

I am still waiting for someone to make a more fully featured diagnostic testing library. There is a sketch in #80 that claims to extend to custom normalization. And assorted closed feature requests under https://github.com/dtolnay/trybuild/labels/out%20of%20scope.
