### ISSUE TITLE
trybuild fails to respect the --target-dir flag

### ISSUE THREAD

**Issue by jaskij** [dtolnay/trybuild#298]
I came across https://github.com/JelteF/derive_more/issues/421 and dug a little - it seems that `trybuild` tries, but fails, to respect the `--target-dir` flag.

Using `derive_more` as an example:

1. make a new directory, say `repro`
2. in that dir, make a fresh clone of `derive-more` (so the source is in `repro/derive-more`)
3. make `repro/test`
4. `cd` into `repro/derive-more`
5. run `cargo test --all-features --target-dir=../test`

The expectation is that all intermediate files are in the target directory as passed on the command line, `repro/test`, and `repro/derive-more/target` does not even get created. That is not the case here.

This apparently cause issues with Debian's build infra, like the issue linked at the top.

**Comment by dtolnay** [comment]
As far as I know, Cargo exposes no way for a test to recover the value passed to `--target-dir`. This is a Cargo flaw (https://github.com/rust-lang/cargo/issues/9661). The Cargo fix would be to define $CARGO_TARGET_DIR during test execution when a particular `--target-dir` chosen.

If you set $CARGO_TARGET_DIR yourself, that should get picked up. You can see it in `CARGO_TARGET_DIR=../test cargo metadata --no-deps --format-version=1 | jq .target_directory`.
