### ISSUE TITLE
Normalize separators in $WORKSPACE paths

### ISSUE THREAD

**Issue by dherman** [dtolnay/trybuild#30]
Thanks again for #29! I'm hitting one more bug, which is that `'\\'` characters in `$WORKSPACE` paths aren't normalized to `'/'` characters, so I can't have a single cross-platform template file that works in both Unix and Windows. The only diff left that's still failing my CI build in Appveyor is:

```
<    ::: $WORKSPACE/src/types/mod.rs:313:39
---
>    ::: $WORKSPACE\src\types\mod.rs:313:39
```

**Comment by dtolnay** [comment]
I would accept a PR to replace '\\' → '/' in any line containing $WORKSPACE, or alternatively any line starting with `:::`. The replacement should happen near the same place that $WORKSPACE is introduced.

**Comment by dherman** [comment]
@dtolnay Would it maybe make sense to do the normalization closer to the logic that [looks at lines beginning with `-->`](https://github.com/dtolnay/trybuild/blob/master/src/normalize.rs#L78-L83)? (Although TBH I'm still not quite understanding how separator-normalization already happens in that context, since I don't see any code doing an n-ary search and replace for separators.)

**Comment by dherman** [comment]
Hm, no, that would cause the `$WORKSPACE` replacement logic to fail since it would normalize separators too soon.

Can you explain why `$DIR` replacement happens in two distinct places in the code? (Namely, `normalize::filter` and `run::Test::run`)

**Comment by dtolnay** [comment]
> Can you explain why `$DIR` replacement happens in two distinct places in the code?

The filepath after `-->` is usually given by rustc as a relative path, so there is one replacement to normalize `/` vs `\` in those lines. There is a different replacement to deal with absolute paths to the source dir, which can sometimes appear in various other output from cargo or rustc or proc macros.

I added some documentation of what's going on in normalize.rs in #31.
