### ISSUE TITLE
Replacing keys with values instead of values with keys?

### ISSUE THREAD

**Issue by dherman** [dtolnay/trybuild#33]
Am I reading the code wrong or did commits 59c0abf1c5969f5031a23ebd9a266c83ccb42773 and 69a0d0de4b645ee83cae546d9145e0be2b054b02 break normalization? The previous logic was replacing values with keys, but it looks like the updated logic replaces keys with values.

**Comment by dherman** [comment]
See https://github.com/dtolnay/trybuild/blob/master/src/normalize.rs#L137-L139

**Comment by dtolnay** [comment]
Fixed in #32. I filed #34 to find a way to catch this kind of bug with tests.
