### ISSUE TITLE
Add inspect method to TestCases

### ISSUE THREAD

**Issue by Robbepop** [dtolnay/trybuild#35]
I am using your `trybuild` in my projects and generally really like it.

## Problem

But during development of more complex proc macros it is still hard to sometimes figure out problems with test cases so you have to move them out into a respective proper test project and expand code there. (Please tell me if there is a simpler approach to this.)

## Proposal

It would be amazing to have something like `TestCases::inspect(path)` to make it print the expanded code into the console log for debugging purposes. The usage scenario here is to have this inspect for more complex tests or macros and once they expand to what you would like to see you can simply change `inspect` to either a pass or failure test.

## Alternative

Your proc macro workshop guides people to always copy their tests into the projects `main.rs`. A solution guided by `TestCases::inspect` (or similar) would feel more integrated to me.

**Comment by dtolnay** [comment]
I think ideally this would be handled by cargo expand, such that if you run `cargo expand --test somename` and it sees that tests/somename.rs exists but "somename" is not one of the test targets listed for the current crate by `cargo metadata`, then it does the trybuild thing to pull out the code to a temp directory and runs rustc against that (just like trybuild would, but with `--pretty=expanded` instead).

Is this something you would be interested in sending a PR for?

**Comment by Robbepop** [comment]
You are right, this would be better and would make more sense to put in `cargo expand`.

> Is this something you would be interested in sending a PR for?

Currently not much time for side projects but if you don't mind I can open an issue there and try implementing it once I have time doing so.

**Comment by dtolnay** [comment]
Sounds good, I wouldn't mind a cargo-expand issue to track this. Thanks!
