### ISSUE TITLE
Allow multiple .stderr variants

### ISSUE THREAD

**Issue by CreepySkeleton** [dtolnay/trybuild#36]
## Summary 
Allow multiple stderr variants to match against, i.e output of `test.rs` will be checked against  `test.stderr.stable`, `test.stderr.beta`, and `test.stderr.nightly` and it will succeed if compilation output matches any of `*.stderr.*` files.

## Motivation
Sometimes compilation errors change for no good reason, especially on nightly. Furthermore, errors on stable may mot be exactly the same as on nightly, just minimal cosmetic mismatches like number of `^^^^`, or bottom `could not compile`  line.

It would be nice to provide multiple stderr samples via `*.stderr.*` files.

## Detailed design
* Every `test.rs` ui test is now associated either with a single `test.stderr` file (current implementation) or multiple `test.stderr.stable`, `test.stderr.nightly`, `test.stderr.*`... 
* If single `test.stderr` file is present `trybuild` should behave just like it currently does.
* If multiple stderr files are present, actual output will be matched against every associated `test.stderr.*` file, match succeeds if the output matched any of this stderr files.
* Single-sample and multiple-samples cannot be used together, this is an error.

**Comment by TeXitoi** [comment]
As maintaining these tests seems more and more complicated, maybe we can just run them on stable and run them only on stable?

**Comment by dtolnay** [comment]
I typically only run ui tests on nightly, using [rustversion](https://github.com/dtolnay/rustversion). Example: https://github.com/serde-rs/json/blob/b63ad147341cc2623833259bc862be1ff29945cc/tests/compiletest.rs

```rust
#[rustversion::attr(not(nightly), ignore)]
#[test]
fn ui() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/ui/*.rs");
}
```

But if this matters to you, I would accept a PR to compare against `$testname.*.stderr`.

**Comment by TeXitoi** [comment]
Seems like a good solution, @CreepySkeleton what do you think?

**Comment by CreepySkeleton** [comment]
@TeXitoi I agree. Do we choose nightly or stable?

**Comment by TeXitoi** [comment]
I don't care, maybe stable to have less maintenance overhead?
