### ISSUE TITLE
Restrict "toml" dependency to <= 0.5.2

### ISSUE THREAD

**Issue by CreepySkeleton** [dtolnay/trybuild#39]
The resent code change in `toml` crate made it require rustc 1.36+.

I see, you just dropped support for older versions, but unfortunately I can't really depend on `trybuild` conditionally (i.e. depending on rustc version, if it's possible please tell me). Features won't help me too because `dev-dependencies` cannot be optional.

Also, it's impossible to work this around by simply stopping running tests on rustc <1.36 because the `toml` crate is going to have to be build one way or another.

The only real options here are either drop support for rustc <1.36 for my crate (highly undesirable) or ditch `trubuild` (even less desirable).

Actually, I don't see any particular reason to move to `toml 0.5.3`. Could you please restrict this dependency and bring support for 1.31 back?

**Comment by dtolnay** [comment]
Can you pin the toml version on your end?

```rust
trybuild = "1.0"
toml = "=0.5.3"
```

I don't really want to get into the super conservative compiler version support game with trybuild. If that doesn't work, the alternative would be you could fork trybuild and maintain the old compiler support in the fork.

**Comment by CreepySkeleton** [comment]
Thanks for the hint, I didn't realized I could do that :) If it won't work out I'll just make my own fork.
