### ISSUE TITLE
Turning `path!` into its own crate

### ISSUE THREAD

**Issue by zertosh** [dtolnay/trybuild#46]
I was looking to implement `Div` for `Path` and came across: https://github.com/rust-lang/rust/pull/62989#issuecomment-515697585, which led me here. The `path!` macro (https://github.com/dtolnay/trybuild/blob/9b92eb13813a6da4c5b135626a52ff18d9d7ba26/src/path.rs) implemented here is really cool. Any chance you can publish that as its own crate?

**Comment by dtolnay** [comment]
It's not something that I am interested in maintaining myself as a crate, but the code is appropriately licensed so that someone else could maintain a fork.

**Comment by zertosh** [comment]
Here it is: https://crates.io/crates/path_macro

**Comment by pickfire** [comment]
Must it be a macro? Why not just `path / "a" / "b"` to become `Path`?
