### ISSUE TITLE
Doesn't work when you are offline and cargo wants to resolve dependencies

### ISSUE THREAD

**Issue by thomaseizinger** [dtolnay/trybuild#50]
Using trybuild doesn't work if cargo wants to resolve dependencies because it is not possible to pass the `--offline` flag to cargo.

Temporarily, I had hacked the local source code and manually added `--offline` which worked! :) (I was on a plane when I experienced this)

I am not sure what the best solution here is. Always passing `--offline` seems like an overkill.
Maybe doing a quick network check upfront and pass the flag if that one fails?

Happy to send a PR if we can outline a solution here.

**Comment by dtolnay** [comment]
Always passing `--offline` would actually be reasonable I think. The Cargo invocation performed by trybuild is always going to be using a subset of the dependencies of the currently running test (the one that calls trybuild), so we know all of those are available in Cargo's local cache.

**Comment by thomaseizinger** [comment]
> Always passing `--offline` would actually be reasonable I think. The Cargo invocation performed by trybuild is always going to be using a subset of the dependencies of the currently running test (the one that calls trybuild), so we know all of those are available in Cargo's local cache.

Yeah, I was thinking that this might be the case but I wasn't really sure. Even easier then :)
I'll send a PR if you don't mind!
