### ISSUE TITLE
Assert error messages

### ISSUE THREAD

**Issue by betamos** [dtolnay/trybuild#55]
As I understand it, `compile_fail` simply checks that compilation fails, but not why. It would be helpful if one could assert that the error output e.g. contains a specific string.

Context: when I'm writing macros, I'm spending a considerable amount of time setting up spans to generate readable error messages.

**Comment by dtolnay** [comment]
That's what compile_fail does. Take a look at https://github.com/dtolnay/trybuild/tree/1.0.24#compile-fail-tests where it talks about .stderr files.

**Comment by betamos** [comment]
Thanks for the quick response, and sorry for the noise. Must have missed it when reading the docs. This is it!
