### ISSUE TITLE
feature request: mode to not assert error messages

### ISSUE THREAD

**Issue by coriolinus** [dtolnay/trybuild#56]
Inverse of https://github.com/dtolnay/trybuild/issues/55. Context: https://github.com/exercism/rust/pull/932.

For our use case, we want to test that arbitrary student macro implementations either successfully compile or fail to compile for a given input, but we really don't care about the particular error message. We don't want to require that students set an environment variable, and don't want to confuse them by generating the `wip` directory.

I'm willing to put some time into implementing this, if it seems like a plausible feature. My approach: add a new method to `TestCases`: `assert_compile_fail`. This function checks compilation status and succeeds or fails as a test case, but does not look for a `*.stderr` file.

**Comment by dtolnay** [comment]
Closing as per https://github.com/dtolnay/trybuild/pull/57#pullrequestreview-383342617.
