### ISSUE TITLE
stderr files are mixed up when two `compile_file()` are run in separate tests

### ISSUE THREAD

**Issue by manuelmorales** [dtolnay/trybuild#58]
Given a file with two tests that each of them invoke `compile_file()` once, when the tests are run  with `cargo test`, Trybuild will sometimes confuse the `stderr` between the different files.

Example of test file:

```rust
use trybuild::TestCases;

#[test]
fn test_1() {
    TestCases::new().compile_fail("compile_failures/1.rs");
}

#[test]
fn test_2() {
    TestCases::new().compile_fail("compile_failures/2.rs");
}
```

When I run `TRYBUILD=overwrite cargo test` I got the following output:

```
$ TRYBUILD=overwrite cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/trybuild_bug-d5914003f188d23e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/compile_failures-de2e248fffe703d4

running 2 tests
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Checking trybuild_bug-tests v0.0.0 (/home/manuel/dev/rust/trybuild_bug/target/tests/trybuild_bug)
    Blocking waiting for file lock on build directory                    ] 0/1: trybuild_bug-tests(bin)                                                                                                    
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s


test compile_failures/1.rs ... 

test compile_failures/2.rs ... wip

NOTE: writing the following output to `compile_failures/1.stderr`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: expected one of `(` or `<`, found `{`
 --> $DIR/1.rs:1:9
  |
1 | fn main { failure_1 }
  |         ^ expected one of `(` or `<` here
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈



test test_1 ... ok
wip

NOTE: writing the following output to `compile_failures/2.stderr`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: expected one of `(` or `<`, found `{`
 --> $DIR/1.rs:1:9
  |
1 | fn main { failure_1 }
  |         ^ expected one of `(` or `<` here
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈



test test_2 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Notice how Trybuild is writing the error output of `1.rs` into `2.stderr`. This happens randomly, it will sometimes pick one, sometimes the other.

See a full repo that reproduces the issue here: https://github.com/manuelmorales/trybuild_file_mixup. I'm using `rustc 1.39.0` on Ubuntu 19.10.

**Comment by manuelmorales** [comment]
Seems like a race condition. Running the tests with `cargo test -- --test-threads 1` makes the problem go away.

**Comment by antifuchs** [comment]
I'm running into the same issue - extracting "positive" tests that should compile on all rustc versions into a single test doesn't work, and so my code has to run the positive & negative tests (where error messages might differ between rustc versions) in the same test function.

It does seem like some sort of non-parallelism-safety issue: The error I get says that a test (which should succeed) succeeded when failure was expected.

**Comment by CraftSpider** [comment]
Looking into this a bit: Every test creates its own mini cargo project. *I think* the issue is that every test uses the same directory and name, meaning that when run in parallel, the writing of the manifest is overlapping. Something like
Thread 1 - Writes manifest, starts cargo
Thread 2 - Writes manifest, starts cargo
Thread 1 - Cargo gets lock, runs test
Thread 2 - Cargo gets lock, runs test
Or other similar situations.
