### ISSUE TITLE
Build test cases in parallel

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/trybuild#6]
I think this would currently be blocked by Cargo. Concurrent invocations of `cargo build` on different binaries in the same project seem to execute one at a time. There may be alternative ways to implement this instead.

**Comment by carlomilanesi** [comment]
I tried this code:
```
let mut threads = vec![];
for i in 0..3 {
    let t = trybuild::TestCases::new();
    threads.push(std::thread::spawn(move || {
        t.compile_fail(format!("tests/ui/name{}*.rs", i));
    }));
}
for thread in threads {
    thread.join().unwrap();
}
```
Though, it does not work, as the second thread to run uses the same stderr file of the first one.

**Comment by dtolnay** [comment]
Implemented in #168.

**Comment by jhpratt** [comment]
When running code coverage I need to pass `--test-threads 1` to cargo, but `trybuild` still runs in parallel now that I've upgraded. Could `trybuild` somehow honor this?

**Comment by taiki-e** [comment]
@jhpratt I think you can set `RUST_TEST_THREADS=1` environment variable.

That said, it seems to be an issue of the `-C instrument-coverage` itself (https://github.com/rust-lang/rust/issues/91092), so I think we need to set that environment variable on the coverage tool (probably cargo-llvm-cov in this case) side.

**Comment by jhpratt** [comment]
`RUST_TEST_THREADS=1` does not help here. For the time being, at least, I'm probably going to do separate runs and [merge them](https://github.com/taiki-e/cargo-llvm-cov#merge-coverages-generated-under-different-test-conditions).
