### ISSUE TITLE
CI passes even when trybuild fails

### ISSUE THREAD

**Issue by pksunkara** [dtolnay/trybuild#62]
```rust
#[test]
fn ui() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/ui/*.rs");
}
```

When the diff is different in any of the fixture, the test should fail, not pass.

**Comment by CreepySkeleton** [comment]
Could you post the content of `tests/ui/*.rs`?

**Comment by pksunkara** [comment]
My bad, I was trying to change something on trybuild and was testing with the modified stuff which led to [this](https://travis-ci.org/github/clap-rs/clap/jobs/673138106#L1430) CI job.

But normally, it's working. CI is failing correctly when any fixture fails.
