### ISSUE TITLE
Check stdout in TestCases::pass

### ISSUE THREAD

**Issue by botika** [dtolnay/trybuild#64]
Could `TestCases::pass` with `stdout` do the same as `TestCases::compile_fail` with `stderr` ?

In the event that the file is present, it will be checked.

**Comment by dtolnay** [comment]
I would be open to a PR that checks stdout if the file exists. Similar to #8.

**Comment by pksunkara** [comment]
How is this issue different with #8? And what's blocking #82 from closing this and #8?

**Comment by dtolnay** [comment]
@pksunkara this issue is about stdout. #8 is about warnings, which are on stderr. I don't think #82 has any relation to this issue.

**Comment by dtolnay** [comment]
Similar to https://github.com/dtolnay/trybuild/issues/8#issuecomment-1078691061, I've changed my mind and no longer interested in building this into this crate. Someone else can support this feature in a different crate if they'd like.

Thanks anyway for the suggestion!
