### ISSUE TITLE
[Suggestion] Pass --manifest-path to Cargo instead of changing the working directory

### ISSUE THREAD

**Issue by abonander** [dtolnay/trybuild#69]
We're using Trybuild in SQLx to run UI tests for the proc macros. When testing SQLite, we want to give a relative path to a test database to use so that the tests are portable, but the only way we have right now to pass this into the proc macro is an environment variable that is set for both regular integration tests as well as UI tests. It's not really possible to provide a relative path that works for both. 

We can work around this of course, but I'm wondering if there's a compelling reason why Trybuild changes the working directory instead of using `--manifest-path` to point Cargo to the generated project, because I think the latter is significantly less surprising.

**Comment by dtolnay** [comment]
I think this wouldn't help your use case because proc macros always execute with the workspace root as the current directory, regardless of where you invoke with --manifest-path from.

**Comment by abonander** [comment]
Ah, I was not aware of that, thank you for the information. And it's not really feasible to dynamically add the generated test project to the workspace, either.

Feel free to close, although if it wouldn't hurt anything this might be a decent first-time contributor issue since it should just be a line or two.
