### ISSUE TITLE
Display macro println output when running tests

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/trybuild#7]
Currently eprintln output from macros will be displayed but println will not. They should both be shown.

**Comment by DevinR528** [comment]
Just to make sure I understand correctly, this would be a matter of changing the term.rs file to also include a Stream::stdout then altering all the print and println to e versions respectively and finally in run.rs passing output.stdout to check via check_pass or check_compile_fail. Obviously i glossed over a few details but just so I am working in the right direction, I wouldn't mind giving this a try.

**Comment by dtolnay** [comment]
Fixed in 1.0.10.
