### ISSUE TITLE
Workspace path expanded in output on Windows

### ISSUE THREAD

**Issue by davidhewitt** [dtolnay/trybuild#73]
I've written a `compile_fail` test which produces slightly different output under Windows versus Linux. https://github.com/davidhewitt/pyo3/runs/725074238

As far as I can tell the diff is that in Linux a path reads `$WORKSPACE` whereas on Windows a full path is printed:

- Linux: `::: $WORKSPACE/src/pyclass.rs:76:80`
- Windows: `::: D:/a/pyo3/pyo3/src/pyclass.rs:76:87`

It's not clear to me whether this might actually be an inconsistency just in the compiler output on the two platforms rather than a `trybuild` issue.

Maybe there's a way I can work around this with some kind of wildcard in my `stderr` file? I couldn't see any mention of such a thing in the `trybuild` documentation.

**Comment by dtolnay** [comment]
I would accept a PR to fix this on windows. The relevant code is https://github.com/dtolnay/trybuild/blob/1.0.27/src/normalize.rs#L106.

**Comment by davidhewitt** [comment]
Thanks for the pointer. I'll take a shot at a PR later..m

**Comment by davidhewitt** [comment]
It seems like this is a case sensitivity issue. On the github actions runner (it's a windows machine using git bash), `echo $(pwd)` prints `/d/a/pyo3/pyo3`.

This lowercase `d` for the drive letter carries forward into the output of `cargo metadata`, which `trybuild` is using to get the workspace root.

The compiler on the other hand is outputting paths with an uppercase drive letter, `D`. This is why `trybuild` doesn't replace it successfully.

A workaround in `trybuild` would be to replace the drive letter with uppercase, if it's lowercase. To be on the safe side we might want to try replacing with both uppercase and lowercase drive letters.

Do you think that's an acceptable strategy for a bugfix?
