### ISSUE TITLE
Ability to specify a different stderr path

### ISSUE THREAD

**Issue by aticu** [dtolnay/trybuild#76]
I have some tests that are generated in a build script.
They are run like so:

```rust
#[test]
fn ui() {
    let t = trybuild::TestCases::new();
    t.compile_fail(concat!(env!("OUT_DIR"), "/tests/*.rs"));
}
```

This however results in the `*.stderr` files being located somewhere in the `env!(OUT_DIR)` directory, which isn't commited into source control.

Now tests for which the output isn't commited into source control are pretty useless, so it would be nice to be able to do something like this: 

```rust
#[test]
fn ui() {
    let t = trybuild::TestCases::new();
    t.compile_fail_with_stderr_dir("tests/ui/*.rs", "tests/ui/stderr");
}
```

Or maybe to allow for other additions in the future without having to add a new function for every addition:

```rust
#[test]
fn ui() {
    let t = trybuild::TestCases::new();
    t.compile_fail_with_options("tests/ui/*.rs", trybuild::TestOptions {
        stderr_dir: "tests/ui/stderr",
        ..Default::default()
    });
}
```

I would be willing to write a PR for either version, if you'd accept it.

**Comment by dtolnay** [comment]
I think I would prefer not to make a change for this, but some reasonable options would be:

- Maintain this functionality in a fork
- Make build script copy the stderr files to out dir, make test copy stderr files back if run with TRYBUILD=overwrite

**Comment by aticu** [comment]
Thanks, you gave me an idea.

In case anyone is curious and has a similar issue, this is what I came up with:

```rust
/// The variable, which enables writing of the tests in the source directory.
///
/// This is explicitly opt-in, because the cargo documentation states
///
/// > In general, build scripts should not modify any files outside of OUT_DIR.
/// > It may seem fine on the first blush, but it does cause problems when you use such crate as a
/// > dependency, because there's an implicit invariant that sources in `.cargo/registry` should be
/// > immutable. cargo won't allow such scripts when packaging.
///
/// However it should be noted, that trybuild with it's `TRYBUILD=overwrite` setting behaves in a
/// similar fashion, so it should be ok.
const MUTABLE_SOURCE_VARIABLE: &'static str = "GENERATE_TESTS";

println!("cargo:rerun-if-env-changed={}", MUTABLE_SOURCE_VARIABLE);

if let Ok(mut val) = std::env::var(MUTABLE_SOURCE_VARIABLE) {
    val.make_ascii_lowercase();
    if val == "yes" || val == "true" || val == "1" {
        generate_tests();
    }
}
```
