### ISSUE TITLE
Warnings verification

### ISSUE THREAD

**Issue by kriomant** [dtolnay/trybuild#8]
I would like to verify warnings same way I verify errors. `compile_fail` can't be used, because compilation passes, and `pass` can't be used because it doesn't check stderr.

Right now I use

```rust
fn main() {
    compile_error!("Warnings verification");
}
```

to always fail and thus check for stderr, but more straightforward way would be apprecated.

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to check a *.stderr file for pass tests if one exists.

**Comment by kriomant** [comment]
Wouldn't it be better to create special `compile_success` tests type which compiles file but doesn't run them and just validates stderr?

**Comment by dtolnay** [comment]
I would prefer not to. What do you see as the advantage of that approach?

**Comment by kriomant** [comment]
1. Clear intention — it's compilation test, not ordinary one.
2. I may want to ensure some code is compiled, but not run it, because it does heavy things, like creating files or connecting to database. How to avoid running code without getting "not used" complaints from compiler? Writing `#[allow(dead_code)]` everywhere is no much better than `compile_error!`.
3. Small, but still speed improvement because binaries shouldn't be loaded and runned.

**Comment by dtolnay** [comment]
Revisiting this quite a bit later, I think I've changed my mind on this issue. I'll leave it to someone else to handle this in a different crate if they'd like. For my own use cases of this crate, a `#![deny(…)]` in the test case is good enough for testing diagnostics that would otherwise be warnings.

Thanks anyway for the suggestion!

**Comment by sam0x17** [comment]
Just wanted to illuminate a use-case for this -- in https://github.com/paritytech/substrate/pull/13224 we generate a number of impls based on a function def with some special markers inside of it, and we ended up also generating a real function definition based on this syntax to ensure that we get compiler warnings if one of the args on that function is not used anywhere in the body (in our case this would indicate a faulty benchmark, so we definitely want to see that warning). Until we started producing a real function definition in addition to the trait impls, we actually weren't getting compiler warnings like this, so for us it would be great to be able to test that these warnings are being issued.
