### ISSUE TITLE
RFC: Strategy API

### ISSUE THREAD

**Issue by tmandry** [dtolnay/trybuild#80]
# RFC: Strategy API
**Summary:** Enable `trybuild` to work in non-cargo environments by customizing the logic used to build, run, and check outputs.

This issue proposes to add a `Strategy` trait to trybuild, allowing a user to run in non-cargo environments (#14). I spent a bit of time prototyping before coming to this particular API, and I’m pretty sure this can be implemented in a way that’s not too disruptive. That said, I wanted to get feedback before doing a full implementation.

The proposed API is below.

```rust
pub trait Strategy: Send + Sync + Debug {
    /// Called once, before running all tests.
    fn prepare(&mut self, tests: &[Test]) -> Result<Project, Box<dyn Error + 'static>>;
    /// Returns a command that can be executed to build the given test.
    fn build(&self, test: &Test) -> Command;
    /// Returns a command that can be executed to run the given test.
    fn run(&self, test: &Test) -> Command;
}

/// Describes an individual test being run.
struct Test { ... }
impl Test {
    /// A unique name for the crate and binary.
    pub fn crate_name(&self) -> String;
    /// Path to the source file.
    pub fn path(&self) -> &Path;
    /// Whether this test requires actually building and running a binary.
    pub fn requires_run(&self) -> bool;
}

/// The default strategy used.
pub struct CargoStrategy { ... }
impl CargoStrategy {
    pub fn new() -> Self;
}
impl Strategy for CargoStrategy { ... }

#[derive(Default)]
#[non_exhaustive]
pub struct Project {
    /// Source directory of the project.
    ///
    /// Occurrences of this are replaced with `$DIR` in compile output.
    pub source_dir: Option<String>,
    /// Source directory of the workspace which contains this project.
    ///
    /// Occurrences of this are replaced with `$WORKSPACE` in compile output.
    pub workspace: Option<String>,
}
```

Finally, a method would be added to `TestCases` to allow passing in a strategy object (maybe `new_with_strategy()`).

# Possible extensions
## Normalization API

After this I’d like to add something like the following API for customizing the normalization strategy. This makes it possible to add your own normalization passes and even to use trybuild with tools besides rustc, which are both use cases I’m interested in.

If this is something you never want in trybuild, that would be good to know 🙂

```rust
pub trait Strategy: Send + Sync + Debug {
    /// ... everything above, plus ...

    /// Normalizes the diagnostics in `output` and returns a version
    /// suitable for saving to a file.
    fn normalize(&self, project: &Project, test: &Test, output: &str) -> String {
        crate::normalize::diagnostics(project, test, output)
    }
  
    /// Checks whether the two outputs `expected` and `actual` are
    /// considered to match.
    fn matches(
        &self, project: &Project, test: &Test, expected: &str, actual: &str
    ) -> bool {
        crate::normalize::matches(project, test, expected, actual)
    }
}

/// Provides normalizing functionality for rustc output.
pub mod normalize {
    pub fn diagnostics(project: &Project, test: &Test, output: &str) -> String;

    pub fn matches(
        project: &Project, test: &Test, expected: &str, actual: &str
    ) -> bool;
}
```

## Parallel execution (#6)

If we want to support parallel test execution, we could added a `supports_parallel()` method to `Strategy`, that returns `false` by default. If needed, we could also add a `prepare_thread()` method. `Strategy` has `Send + Sync` supertraits so these bounds don’t become a problem in the future.

**Comment by dtolnay** [comment]
Thanks for putting together this proposal! I think I would prefer not to maintain that API as part of this crate, but it would be awesome for someone to build it as its own crate (trybuild fork or clean slate).

**Comment by tmandry** [comment]
I thought that might be the case :)
Sounds good, I may do that. Closing for now.
