### ISSUE TITLE
changes to library files can still bleed through subtly

### ISSUE THREAD

**Issue by ahl** [dtolnay/trybuild#86]
Let me start by saying this isn't a big deal.

#85 (thank you!) removed `$WORKSPACE`-related line numbers, but the output can still change spuriously when library source files cross ⌊log_10⌋ boundaries. For example, in the output below, the file `handler.rs` just went over 1000 lines:

```diff
-   --> $DIR/bad_endpoint6.rs:22:8
-    |
-22  |     Ok(HttpResponseOk(Ret { "Oxide".to_string(), 0x1de }))
-    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `Ret`
-    |
-   ::: $WORKSPACE/dropshot/src/handler.rs
-    |
-    | pub struct HttpResponseOk<T: JsonSchema + Serialize + Send + Sync + 'static>(
-    |                                           --------- required by this bound in `dropshot::handler::HttpResponseOk`
+    --> $DIR/bad_endpoint6.rs:22:8
+     |
+22   |     Ok(HttpResponseOk(Ret { "Oxide".to_string(), 0x1de }))
+     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `Ret`
+     |
+    ::: $WORKSPACE/dropshot/src/handler.rs
+     |
+     | pub struct HttpResponseOk<T: JsonSchema + Serialize + Send + Sync + 'static>(
+     |                                           --------- required by this bound in `dropshot::handler::HttpResponseOk`
```

The only way that occurs to me to fix this would require multiple passes. I think the simplest option would be to post-process looking to see if all lines match `([ ]*-->|\d*[ ]*[ ]+  |[ ]*:::).*`. In that case one could trim one or more '` `'s from each line.

Happy to submit a PR 1. this is worth fixing and 2. that approach sounds reasonable.

**Comment by dtolnay** [comment]
I would accept a PR to fix this. Around above [this line](https://github.com/dtolnay/trybuild/blob/f6407d0f4d1acea829dc8f9cf3e4d9c3b6dde87b/src/normalize.rs#L133) you'd be able to scan forward whether every line until the next blank line matches your pattern, and if so, decide how many spaces to be removed. Save that in a field of Filter and every subsequent line could delete the first *n* spaces from the line, until reset to 0 by a blank line.
