### ISSUE TITLE
[Feature Request] Support compilers other than rustc/cargo

### ISSUE THREAD

**Issue by Kixiron** [dtolnay/trybuild#87]
Trybuild is a wonderful library for compiler testing with really useful features and nice-looking output, and being able to use it for general compiler testing instead of *just* rustc would be amazing

I'd be happy to work on this as well if I got pointed in the right direction

**Comment by dtolnay** [comment]
I would prefer not to maintain that as part of this crate, but I would welcome someone forking to build that.

#80 has some design work in this direction.
