### ISSUE TITLE
DIR path not expanded for mutual parents

### ISSUE THREAD

**Issue by jhwgh1968** [dtolnay/trybuild#89]
I am currently working on a project with the following directory structure:

```
rhai/
    Cargo.toml
    src/
    ...
    codegen/
        Cargo.toml
        ui_tests/
        ...
```

As one might expect, the `codegen` crate requires importing the parent crate.

This works well, except when a UI test gets an error message pointing to the parent crate. Since it does not match any of the current canonicalization rules, it puts in the absolute path... specific to my PC. For example:

https://github.com/schungx/rhai/blob/d8e85df9dcea9b3f1f277e1823589a044d9306b8/codegen/ui_tests/rhai_mod_non_clonable_return.stderr#L7

When I tried to merge this change to the project's CI, it failed because the CI was looking for an error message that pointed to _its_ absolute path.

I am working on a change to fix this. It finds the common prefix path between the error message and the working directory, and canonicalizes that as a relative path. In the example error above, the path would become `$DIR/../../src/any.rs`.

This is a bit of a niche case, I admit. My question is, would a patch for this be accepted?

**Comment by dtolnay** [comment]
Normally that project arrangement would have a workspace root at the outer Cargo.toml.

```toml
[workspace]
members = ["codegen"]
```

We do get a portable test in that case:

```console
error[E0277]: the trait bound `NonClonable: Clone` is not satisfied
   --> $DIR/rhai_mod_non_clonable_return.rs:12:12
    |
12  |     pub fn test_fn(input: f32) -> NonClonable {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `NonClonable`
    |
   ::: $WORKSPACE/src/any.rs
    |
    |     pub fn from<T: Variant + Clone>(value: T) -> Self {
    |                              ----- required by this bound in `rhai::Dynamic::from`
```

**Comment by jhwgh1968** [comment]
Oh! I didn't know you could do a workspace directive within another crate's Cargo.toml.

Thanks, @dtolnay. I'll close this and do that instead.
