### ISSUE TITLE
Allow expecting a runtime panic

### ISSUE THREAD

**Issue by ninevra** [dtolnay/trybuild#96]
Suppose a macro expands to a block which asserts invariants at runtime, e.g. using `assert!()`. It might be useful to be able to test that the macro's expansion compiles successfully even though it will panic at runtime.

Neither `pass()` nor `compile_fail()` expresses this; perhaps a `runtime_fail()` function could be added?

Checking a `.stderr` file could also be useful in this case, to ensure that the panic is communicated effectively.

**Comment by PoignardAzur** [comment]
Agreed. This is definitely something I could use with my macros.

**Comment by dtolnay** [comment]
I would prefer not to build this into trybuild. Testing panic messages of successfully compiled code is already covered by `#[should_panic(expected = "...")]` in ordinary unit tests / integration tests, or by `catch_unwind` + assertions on the resulting error object for any more complicated assertions.
